<Idoctype! HTML>
<html>
	<head>
		<title></title>
	</head>
	<body>
		<img src="https://www.freecatphotoapp.com/your-image.jpg" alt"chiboy">
		<main>
<a href="https://www.freecodecamp.org">this links to freecodecamp.org</a>		
			<h1>i love you</h1>
			<h1> i  love vera</h1>
		</main>
		<ul>
  			<li>meat</li>
  			<li>fish</li>
  			<li>Rat</li>
		</ul>
		 <ol>
    		<li>rat</li>
    		<li>noise</li>
   			 <li>light</li>

  		</ol>

  		<form action="https://freecatphotoapp.com/submit-cat-photo">
  		   <input type="text" placeholder="cat photo URL">
  		   <button type="submit"> submit</button>


        </form>
	</body>
</html>	